### ISSUE TITLE
Separate login and register pages

### ISSUE THREAD

**Issue by ilumos** [jamesread/lanlist#11]
Having them both on one page confuses password manager autofill and autosubmit

Separating the pages might also make the code easier to maintain

**Comment by jamesread** [comment]
Hey @ilumos , yeah, I totally agree, this was bugging me too! I've just pushed a commit to the dev site, would you mind checking it over and sharing your thoughts? If you give it the thumbs up I'll push it to the dev site.

https://dev.lanlist.info

**Comment by raz3r83** [comment]
Looks and feels way better, I use a password manager but don't have it set to auto fill but when I tell it to fill in it appears to work as expected.

**Comment by jamesread** [comment]
Pushed this live :-)
