### ISSUE TITLE
Add form validation for event start and end date and time

### ISSUE THREAD

**Issue by ilumos** [jamesread/lanlist#3]
Make both fields required to avoid SQL error

**Comment by jamesread** [comment]
There is an updated date picker now which should really solve things;

![image](https://github.com/jamesread/lanlist.org/assets/2025715/12295cbf-bd4d-45a3-89d6-8fb1314767a9)

Are you still able to reproduce this error though?

**Comment by ilumos** [comment]
Great! No, I've not been able to reproduce the issue since.
