### ISSUE TITLE
Enhancement - Change List view default sorting to Start Date

### ISSUE THREAD

**Issue by raz3r83** [jamesread/lanlist#5]
As per the title change the default sorting on the list view to show events by start date with newest on the top.
![image](https://github.com/jamesread/lanlist.org/assets/24259311/a21efc01-5cb3-411d-8440-bd0f40bbdc43)

**Comment by jamesread** [comment]
Hey, I don't know why that didn't come up before, done! (also used a more human-readable) date format;

![image](https://github.com/jamesread/lanlist.org/assets/2025715/f7f0d850-77cf-4fb7-af3f-d7f489e99c3d)
