### ISSUE TITLE
Moderator Permissions

### ISSUE THREAD

**Issue by raz3r83** [jamesread/lanlist#7]
Issue Area - Organizations

No way to list all Organizations
Cannot Edit Organizations other than my own.

Issue Area - Venues
I can see the United Kingdom count is 17 but currently only 2 show
Of the 2 venues I can see I can only edit my own

Issue Area - Events
From the main page list I can only see published/approved events 
I can edit all events but see nothing to mark it as published/approved

Under my profile I can see sections for Venues / Events / System 
Should there be a section for Organization?

Site Checks I think was showing a few events that were not as yet published but again no way to publish them.

Logs straight up errors with.
Error!
PHP display_errors is turned on, this is the full error message;

Message: Class "PermissionsException" not found
Code: 0
Line: 10
File: /var/www/html/lanlist.org/listLogs.php
Stacktrace: Empty
Trigger: Exception -> Error

**Comment by jamesread** [comment]
Hey @raz3r83 .

Organizations - only the list of "published" organizations was showing, I've set it to show the full list now.

Venues - the same thing wsa happening.

Publishing events - Granted the moderators group "TOGGLE_EVENT_PUBLISHED" privilege, you'll see a "Publish" link in the sidebar of events now.

Site checks - publishing - same as above.

Logs - Removed the "PermissionsException" class, and gave moderators the "VIEW_LOGS" permission.


Let me know if that covers everything for you?

**Comment by raz3r83** [comment]
Hi,

So I can see that the lists are now returning more records so that's good.

No option for modifying other organizations, venues and I can't see an option to publish an event.

I am assuming you want Moderators to be able to make corrections to an Organization and Venues. other potential issues/actions I can think of that might need correcting is being able to associate users with org's and events with org's.

The first event I created was before having setup an org or venue so it wasn't really complete. To be fair this is already covered by editing an event as I can see the Org and Venue drop downs and see the complete lists.

Logs still gives an error:

<html>
<body>
<h1 style="font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; background-color: red; color: white; margin: 0px; padding: 0.5em; font-size: 12pt;">Error!</h1><p style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">PHP display_errors is turned on, this is the full error message;</p><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Message:<span> </span></strong><span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 188, 186); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">You dont have the privs to do this.</span><br style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Code:<span> </span></strong><span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 188, 186); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">0</span><br style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Line:<span> </span></strong><span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 188, 186); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">219</span><br style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">File:<span> </span></strong><span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 188, 186); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">/var/www/html/lanlist.org/includes/functionality/misc.php</span><br style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Stacktrace:</strong><br style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><blockquote style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
ID | File | Line | Class | function call
-- | -- | -- | -- | --
1 | /var/www/html/lanlist.org/listLogs.php | 9 | (none) | requirePriv()

</blockquote><strong style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Trigger:<span> </span></strong><span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 188, 186); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Exception -&gt; Exception</span>
</body>
</html>

**Comment by jamesread** [comment]
Heya,

Okay, so moderators were missing lots of permissions! 

You will need to logout and back in again, but I've just granted moderators: EDIT_ORGANIZER, EDIT_VENUE, JOIN_REQUESTS, CREATE_ORGANIZER (most users can only create one organizer), CREATE_EVENTS (this allows you to specify the organzier at creation time), USERLIST and GROUPLIST. 

I can't actually tell easily how different moderators are to admins (just me), because as an admin I have the SUPERUSER permission which bypasses all permissions checks. I am not trying to keep the good stuff for myself, actually my intent is that moderators have basically access to everything on the site to adjust the database as needed,. 

I'm only guarding moderators from not using some features of the site with permissions checks for things that are not yet stable, or that just wouldn't make sense - such as the News and Scheduled Tasks feature (not using either at the moment). 

Let me explain what you should see, per your comments now; 

> No option for modifying other organizations, venues and I can't see an option to publish an event.

Granted the "EDIT_ORGANIZER" permission (which would help!), you should now see this in the sidebar when you click on an Organzer's profile;

![image](https://github.com/jamesread/lanlist/assets/2025715/c0ef1d2a-2640-47c5-8818-2101b1fd72ad)

> I am assuming you want Moderators to be able to make corrections to an Organization and Venues.

Granted the "EDIT_VENUE" permission (which would also help!);

![image](https://github.com/jamesread/lanlist/assets/2025715/f5d5809e-2205-4fb5-b279-0792f1a2c046)

> Logs still gives an error:

I just checked with my moderator account and it seems to work OK - I did quite a lot to fix up  the audit log etc recently, so probably fixed the error accidently!

**Comment by jamesread** [comment]
@ilumos ping FYI, as my other moderator!

**Comment by raz3r83** [comment]
@jamesread Looking good I can see the options to edit and create Org's and Venues now, creating events shows both the venue and org fields as expected.

Relating users to org's I assume is controlled by the Join requests.

I can see users now but no option to edit them, only reason for doing so would be email address correction and possibly to reset password seeing as there isn't a forgot password function on the login page.

My preference for that if you do add a function to reset the users password is something randomly generated and emailed direct to the user (I would have no reason to see it) obviously only works if they added a correct email address.

Groups I can see but not modify but I think that's as it should be and should remain something for the admin to manage.

You might want to consider another admin at some point but there should be very little a moderator couldn't deal with or work around for now.

1 question can a user be associated with multiple organizations?

**Comment by jamesread** [comment]
> Relating users to org's I assume is controlled by the Join requests.

> I can see users now but no option to edit them, only reason for doing so would be email address correction and possibly to reset password seeing as there isn't a forgot password function on the login page.

Actually I just added EDIT_USER. 

> My preference for that if you do add a function to reset the users password is something randomly generated and emailed direct to the user (I would have no reason to see it) obviously only works if they added a correct email address.

Yeah, I need to add some password recovery options, at the moment you've got access to set a new password, but I think changing that to just "email the new password" might be better. 

> Groups I can see but not modify but I think that's as it should be and should remain something for the admin to manage. 

Yeah, I'll control usergroups for now. 

> You might want to consider another admin at some point but there should be very little a moderator couldn't deal with or work around for now. 

Yep, I like the idea of backups, and not just one person having control, too. While we're building things up though and checking site functionality, I'll stay as the only "SUPERUSER", but be assured that Moderators basically have 99% of the permissions now. Again I'm just not giving permissions on out features that are unused, or broken things, or dangergrous things - and there aren't many of those things to be honest! 

> 1 question can a user be associated with multiple organizations?

No, I did think about adding this, but it's going to be fairly rare that there is a user as an admin of multiple LANs. It will happen, but for now those people will either need to delegate to other admins of those LANs, or create separate user accounts.

There are several permissions checks which are just way easier if a user can only be a member of 1 organization. We'll see if there is enough demand to change that.

**Comment by raz3r83** [comment]
As per DM, can't see an option to edit the user, but then when viewing another user there is no side panel at all which might be why. 

Totally agree on the limit admin for now, I wasn't pushing for it, just throwing it onto the heap to be considered later.

I think someone mentioned being co-owner of two lans, but I think they are an exception.
Possibly it might make sense that for those cases maybe they become moderators, that or otherwise have to do something with groups  but defo a pain to implement, you would need to consider parent organizations as a relationship level at the very least.
Ignore for now unless something comes up.

**Comment by jamesread** [comment]
Awesome, I think we resolved everything now (the last edit user issue was a typo in a permissions check!), thanks SO much for providing feedback, and being a moderator!
