### ISSUE TITLE
Permission Error trying to delete an incomplete Event

### ISSUE THREAD

**Issue by raz3r83** [jamesread/lanlist#8]
Error!
PHP display_errors is turned on, this is the full error message;

Message: Class "PermissionsException" not found
Code: 0
Line: 71
File: /var/www/html/lanlist-prod/misc.php
Stacktrace: Empty
Trigger: Exception -> Error

**Comment by jamesread** [comment]
Hey @raz3r83 , I've updated this quite a bit in the last few days, and removed the old non-existant PermissionsExceptions and hopefully replaced with much friendlier error messages. Resolving this issue as I think it's just historical.
